version: '3.1'

volumes:
  rabbitmq:
  mongodb:

services:
  rabbitmq:
    image: sulemanhasib43/rabbitmq-prometheus:3.1-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongodb:/data/db
  paywall:
    image: localhost:5000/goonj_paywall_v2:2.0.0
    restart: always
    ports: 
      - 5000:5000
